== AMV Protocol

The AMV protocol will utilize existing mechanisms for transport coordinated with JSON formatted messaging.

[[xml_figure3]]
.Protocol Layering
[align=center,alt=,type=]

....

+-----------------------------------------------+
| JSON Formatted AMVP request/response messages |
+-----------------------------------------------+
| HTTP[S] message transfer and signaling        |
+-----------------------------------------------+
| TLS for transport security (recommended)      |
+-----------------------------------------------+
| TCP for transport                             |
|_______________________________________________|

....

[[uriComposition]]
=== HTTP URI Hierarchy

[[uriDiagram]]
[align=center,alt=,type=]
....
        +-------------+------+-----------+
        |   server    |path  | resource
        |             |prefix|
        +-------------+------+-----------+
https://amvts.nist.gov/amvp/v1/certRequests
        +-------------+------+-----------+
                       version


....

Note that deployments utilizing AMV Proxy server *MAY* use a different protocol, e.g., HTTP, custom server, context and port number to interact with the DUT.

[[uriResources]]
=== HTTP URI Resources

In the table below, any parts of a resource path enclosed in curly braces, { or }, are replaced by an instance of what is described in the braces. For example {requestId} could be replaced with 1.

An empty cell for a resource and HTTP Method combination denotes that the server returns an HTTP Status 405 code _Method not allowed (405)_.

[[uri_table]]
[cols="<,<,<,<,<"]
.Resources and their Available Operations
|===
| Resource | GET (read) | POST (create) | PUT (update) | DELETE
| /certRequests | | <<certRequest_post>> | |
| /modules/{moduleId} | <<module_get>> | | |
| /certRequests/{certRequestId} | <<certRequest_get>> | | | 
| /certRequests/{certRequestId}/prerequisiteCertificates | | <<certRequest_post>> | |
| /certRequests/{certRequestId}/evidence | | <<certRequest_post>> | |
| /certRequests/{certRequestId}/sourceCode | | <<certRequest_post>> | |
| /certRequests/{certRequestId}/securityPolicy | <<certRequest_get>> | <<certRequest_post>> | <<certRequest_put>> |
| /certRequests/{certRequestId}/securityPolicy/template | | <<certRequest_post>> | |
| /certRequests/{certRequestId}/otherDocumentation | | <<certRequest_post>> | |
| /certRequests/{certRequestId}/certify | | <<certRequest_post>> | |
| /schemas/{endpoint} | <<schemas_get>> |  | |
| /schemas/{endpoint}/{version} | <<schemas_get>> | | |
|===

The resource path is appended to the path prefix to form the URI used with an HTTP Method to perform the desired AMVP operation. For example to create a new test session using the "/certRequests" resource is "/amvp/v1/certRequests" (assuming an empty context). To create a new certificate request session, the AMVP client would use the following HTTP request-line:

`POST /amvp/v1/certRequests HTTP/1.1`
