
== Certificate Request Evidence Set Expiration

Evidence Sets associated with a crSession can expire. For example, if left incomplete for a period of time. Expiration is a server specific definition which depends on database costs, need for artifacts, etc. If the evidence set has expired, the server will reply with an expired response when the client attempts to download the evidence set:

[source,json]
....
[
    {
        "crSession": 42,
        "status": "expired"
    }
]
....

The AMV protocol requires server implementations to specify test evidence and retain the data while the AMVP client processes and returns the results. Some crypto modules implementing the client-side AMVP protocol may not return results immediately. The AMVP protocol design implies the server must retain the test values to verify the client test responses at some time in the future. However, some test evidence sets are fairly large, which could place significant storage requirements on AMVP server implementations. To alleviate long term storage requirements, AMVP allows for an expiration timestamp to be set when a test evidence set is generated by the server.

The evidence set expiration timestamp must be included by the server in the evidence set when the client downloads the evidence set. The server may change the expiration timestamp of a previously issued evidence set to extend its lifetime subject to server policy. The expiration timestamp must be in the 'expiry' JSON value, which is included in the JSON encoded evidence set. The expiry JSON value will be a string value of the UTC timestamp using form "YYYY-MM-DD HH:MM:SS". The following figure shows a partial JSON encoded evidence set that contains the expiry value.

[source,json]
....
[
    {
        "crSession": 1437,
        "expiry": "2018-12-31 23:59:59",
        "revision": "1.0.0",
        .
        .
        <remainder of evidence set omitted from figure>
        .
        .
            .
        }
]
....
